-- ========================================================
-- DATABASE SCHEMA: PlusBienes CRM
-- Last Updated: 2026-05-17
-- ========================================================

-- 1. Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Authentication & Authorization System
-- --------------------------------------------------------

-- Roles Table
CREATE TABLE IF NOT EXISTS public.roles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT UNIQUE NOT NULL, -- 'ADMIN', 'AGENT', 'USER'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Permissions Table (Optional)
CREATE TABLE IF NOT EXISTS public.permissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT UNIQUE NOT NULL, -- 'crear:propiedad'
    slug TEXT UNIQUE NOT NULL, -- 'properties:create'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Users Table (Custom Auth with bcrypt)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- Hash de bcrypt
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User-Roles Mapping (Many-to-Many)
CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role_id UUID REFERENCES public.roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Profiles Table (Public/Business info)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    avatar_url TEXT,
    phone TEXT,
    bio TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Business Logic Tables
-- --------------------------------------------------------

-- Leads Table (Captación de clientes)
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name CHARACTER VARYING,
    email CHARACTER VARYING,
    phone CHARACTER VARYING,
    property_address CHARACTER VARYING,
    property_type CHARACTER VARYING,
    message TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'contacted', 'resolved')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Properties Table (Inmuebles)
CREATE TABLE IF NOT EXISTS public.properties (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'sold', 'archived')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Initial Data (Seed)
-- --------------------------------------------------------
INSERT INTO public.roles (name, description) VALUES 
('ADMIN', 'Acceso total al sistema y gestión de usuarios'),
('AGENT', 'Gestión de propiedades y captación de leads'),
('USER', 'Cliente final con acceso a favoritos y consultas')
ON CONFLICT (name) DO NOTHING;

-- 5. Automation (Triggers)
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();
CREATE TRIGGER properties_updated_at BEFORE UPDATE ON public.properties FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- 6. Security (RLS Policies)
-- --------------------------------------------------------

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- Users: Only self
CREATE POLICY "Users can see their own auth data" ON public.users
    FOR SELECT USING (id = auth.uid());

-- Profiles: Publicly viewable, editable by owner
CREATE POLICY "Profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (id = auth.uid());

-- Leads: Public can insert, only admins/agents can view
CREATE POLICY "Public leads can be created" ON public.leads
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins and Agents can view leads" ON public.leads
    FOR SELECT USING (true); -- Placeholder: In practice, use a function to check role

-- Properties: Public can view active, admins can manage
CREATE POLICY "Public can view active properties" ON public.properties
    FOR SELECT USING (status = 'active');
